apiVersion: v1
kind: Service
metadata:
  name: microservice-movimiento-service
  labels:
    name: microservice-movimiento-service
    app: microservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: microservice-movimiento
    type: microservice